const WHATSAPP_NUMBER='5583998709157';
let cart=JSON.parse(localStorage.getItem('abi_cart')||'[]');
let favorites=JSON.parse(localStorage.getItem('abi_favorites')||'[]');
let discountValue=0;
const money=v=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
function saveCart(){localStorage.setItem('abi_cart',JSON.stringify(cart));updateCart();}
function addToCart(id){const product=PRODUCTS.find(p=>p.id===id);const found=cart.find(i=>i.id===id);found?found.qty++:cart.push({...product,qty:1});saveCart();toast(`${product.name} adicionado ao pedido`);openCart();}
function changeQty(id,delta){const item=cart.find(i=>i.id===id);if(!item)return;item.qty+=delta;if(item.qty<=0)cart=cart.filter(i=>i.id!==id);saveCart();}
function removeItem(id){cart=cart.filter(i=>i.id!==id);saveCart();}
function toggleFavorite(id){favorites.includes(id)?favorites=favorites.filter(f=>f!==id):favorites.push(id);localStorage.setItem('abi_favorites',JSON.stringify(favorites));renderProducts();}
function updateCart(){const box=document.getElementById('cartItems');const badges=document.querySelectorAll('.cart-badge');const qty=cart.reduce((s,i)=>s+i.qty,0);badges.forEach(b=>b.textContent=qty);if(!box)return;if(!cart.length){box.innerHTML='<p class="text-center text-secondary mt-4">Seu carrinho está vazio.</p>'}else{box.innerHTML=cart.map(i=>`<div class="cart-item"><div><strong>${i.name}</strong><br><small>${money(i.price)} cada</small><div class="qty"><button onclick="changeQty(${i.id},-1)">-</button><span>${i.qty}</span><button onclick="changeQty(${i.id},1)">+</button><button onclick="removeItem(${i.id})" title="Remover"><i class="fa-solid fa-trash"></i></button></div></div><strong>${money(i.price*i.qty)}</strong></div>`).join('')}
const subtotal=cart.reduce((s,i)=>s+i.price*i.qty,0);const delivery=cart.length?5:0;const total=Math.max(0,subtotal+delivery-discountValue);document.getElementById('subtotal').textContent=money(subtotal);document.getElementById('delivery').textContent=money(delivery);document.getElementById('discount').textContent=money(discountValue);document.getElementById('total').textContent=money(total);}
function applyCoupon(){const c=document.getElementById('couponInput').value.trim().toUpperCase();const subtotal=cart.reduce((s,i)=>s+i.price*i.qty,0);const map={ABI10:.10,FAMILIA15:.15,SMASH8:.08,PRIME12:.12};discountValue=map[c]?subtotal*map[c]:0;document.getElementById('cartFeedback').textContent=discountValue?'Cupom aplicado com sucesso.':'Cupom inválido.';updateCart();}
function finishOrder(){const name=document.getElementById('clientName').value.trim();const address=document.getElementById('clientAddress').value.trim();const payment=document.getElementById('paymentMethod').value;if(!cart.length){document.getElementById('cartFeedback').textContent='Adicione itens ao carrinho antes de finalizar.';return}if(!name||!address||!payment){document.getElementById('cartFeedback').textContent='Preencha nome, endereço e forma de pagamento.';return}const subtotal=cart.reduce((s,i)=>s+i.price*i.qty,0),delivery=5,total=Math.max(0,subtotal+delivery-discountValue);const items=cart.map(i=>`${i.qty}x ${i.name} - ${money(i.price*i.qty)}`).join('\n');const text=`Olá, gostaria de fazer este pedido na ABI Burguer:\n\n${items}\n\nSubtotal: ${money(subtotal)}\nEntrega: ${money(delivery)}\nDesconto: ${money(discountValue)}\nTotal: ${money(total)}\n\nNome: ${name}\nEndereço: ${address}\nPagamento: ${payment}`;window.open(`https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(text)}`,'_blank');}
function openCart(){document.getElementById('cartDrawer').classList.add('open')}
function closeCart(){document.getElementById('cartDrawer').classList.remove('open')}
function toast(msg){const t=document.getElementById('statusToast');if(!t)return;t.querySelector('span').textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
